### ISSUE TITLE
2.0 Epic - User Story - Create Account

### ISSUE THREAD

**Issue by MugillaGurilla** [SamuelTheSpartan/Week7Project#8]
**_Working on: Lucas and Cormac_**

ORIGINAL USER STORY

2 AS user
I WANT TO create an account
SO THAT only I can access my account

EPIC
Create Account

2.1 AS a new user
I WANT TO signup on the system
SO THAT so I have an account

- [ ] 2.1.1 Scenario: Create Account with valid First Name, Last Name, Email, Password and Confirmed Password

	Given I am on the create new customer account page
	And I have entered a valid First Name
	And I have entered a valid Last Name 
	And I have entered a unregistered Email
	And I have entered a valid Password
	And I have entered a valid Password Confirmation
	When I click the create an account button
	Then I should land on the account page

- [ ] 2.1.2 Scenario: Create Account with invalid First Name, Last Name and valid Email, Password and Confirmed Password

	Given I am on the create new customer account page
	And I have entered a invalid First Name with a semi colon
	And I have entered a invalid Last Name with a semi colon
	And I have entered a unregistered Email
	And I have entered a valid Password
	And I have entered a valid Password Confirmation
	When I click the create an account button
	Then I should see an error message

- [ ] 2.1.3 Scenario: Create Account with valid First Name, Last Name and Email and Password and Confirmed Password with less than 8 characters

	Given I am on the create new customer account page
	And I have entered a valid First Name
	And I have entered a valid Last Name
	And I have entered a unregistered Email
	And I have entered a Password with less than 8 characters 
	And I have entered a Password Confirmation less than 8 characters 
	When I click the create an account button
	Then I should see an error message that contains "Minimum length of this field must be equal or greater than 8 symbols

- [ ] 2.1.4 Scenario: Create an account with already registered Account Details

**Comment by SamuelTheSpartan** [comment]
Write the 2.0 create account user story into an epic. 
Then derive refined user stories from it. 
Pull the framework from github
Write the gherkin scripts using specflow and run the tests
